# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('law_firm', '0013_auto_20171005_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_customer_profile_id', models.CharField(max_length=20)),
                ('payment_profile_id', models.CharField(max_length=20)),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_firm.LawFirm')),
            ],
        ),
    ]
