# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-02 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
