# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-02 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_customerprofile_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='payment_type',
            new_name='payment_method',
        ),
    ]
