# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0003_auto_20180502_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='payment_profile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
